# Generated by Django 6.0.2 on 2026-02-28 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serveurcei', '0003_alter_electeur_numero_electeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_recus', to='serveurcei.candidat')),
                ('electeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote_effectue', to='serveurcei.electeur')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
    ]
