# Generated by Django 6.0.2 on 2026-02-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('parti_politique', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('cautionnement_valide', models.BooleanField(default=False, verbose_name='Caution de 50M payée')),
                ('photo', models.ImageField(upload_to='photos_candidats/')),
                ('extrait_naissance', models.FileField(upload_to='documents_candidats/')),
                ('casier_judiciaire', models.FileField(upload_to='documents_candidats/')),
            ],
            options={
                'db_table': 'candidats',
            },
        ),
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=150)),
                ('numero_cni', models.CharField(max_length=20, unique=True)),
                ('date_naissance', models.DateField()),
                ('telephon', models.CharField(max_length=20, unique=True)),
                ('numero_electeur', models.CharField(editable=False, max_length=12, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'electeurs',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveurcei.candidat')),
                ('electeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveurcei.electeur')),
            ],
        ),
    ]
