# Generated by Django 6.0.2 on 2026-02-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serveurcei', '0001_initial'),
    ]

    operations = [
    ]
