# Generated by Django 6.0.2 on 2026-02-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveurcei', '0002_auto_20260226_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electeur',
            name='numero_electeur',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
