# Generated by Django 6.0.2 on 2026-02-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveurcei', '0003_alter_electeur_numero_electeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='electeur',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electeur',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True),
        ),
    ]
