# Generated by Django 6.0.2 on 2026-02-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serveurcei', '0004_electeur_region_electeur_sexe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
