# Generated by Django 6.0.2 on 2026-03-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveurcei', '0005_delete_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_votes', models.IntegerField(default=0)),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rang', models.IntegerField(default=0)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='serveurcei.candidat')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['rang'],
            },
        ),
    ]
