# Generated by Django 6.0.2 on 2026-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveurcei', '0006_resultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='electeur',
            name='empreinte_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterModelTable(
            name='electeur',
            table=None,
        ),
    ]
