# Generated by Django 6.0.2 on 2026-03-28 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveurcei', '0007_electeur_empreinte_hash_alter_electeur_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('jeton_hash', models.CharField(max_length=64, unique=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_recus', to='serveurcei.candidat')),
            ],
            options={
                'db_table': 'bulletins_vote',
            },
        ),
        migrations.CreateModel(
            name='ParticipationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('jeton_utilise', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('electeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='serveurcei.electeur')),
            ],
            options={
                'db_table': 'participations_vote',
            },
        ),
    ]
