# Generated by Django 6.0.2 on 2026-04-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveurcei', '0008_bulletinvote_participationvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Administrateur CEI',
                'verbose_name_plural': 'Administrateurs CEI',
            },
        ),
        migrations.CreateModel(
            name='ElectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_election', models.CharField(default='Élection Présidentielle', max_length=200)),
                ('date_debut_vote', models.DateTimeField(blank=True, null=True)),
                ('date_fin_vote', models.DateTimeField(blank=True, null=True)),
                ('vote_actif', models.BooleanField(default=False)),
                ('inscription_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration élection',
            },
        ),
        migrations.AlterField(
            model_name='bulletinvote',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletinvote', to='serveurcei.candidat'),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serveurcei.admincei')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
