# Generated by Django 6.0.2 on 2026-04-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveurcei', '0009_admincei_electionconfig_alter_bulletinvote_candidat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electeur',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
