# Generated by Django 6.0.2 on 2026-04-28 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveurcei', '0010_electeur_is_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='electeur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidat', to='serveurcei.electeur'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='casier_judiciaire',
            field=models.FileField(blank=True, null=True, upload_to='casiers/'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='cautionnement_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='extrait_naissance',
            field=models.FileField(blank=True, null=True, upload_to='extraits/'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidats/'),
        ),
        migrations.AlterModelTable(
            name='candidat',
            table=None,
        ),
    ]
